rule_validation addes
team-macao/macao pull request #15
Opened 2019-12-14 15:08 UTC by MaciejPoland

Validation of rules added when Player is putting a card from hand to table.
Validation of rules added when first card is putted on table.

2019-12-15 08:54 UTC, MateuszKarolChrusciel requested changes
please correct as discussed

2019-12-15 12:59 UTC, MateuszKarolChrusciel requested changes

2019-12-15 12:59 UTC, MateuszKarolChrusciel commented on macao.py
> +                self.table.append(self.deck.pool.pop(random.randint(0, len(self.deck.pool) - 1)))
pls correct

2019-12-15 12:59 UTC, MateuszKarolChrusciel commented on macao.py
> +        while correct_table == False:
while correct_table == False: -> while not correct_table:

2019-12-15 12:59 UTC, MateuszKarolChrusciel commented on macao.py
> -        self.table.append(self.deck.pool.pop(random.randint(0, len(self.deck.pool) - 1)))
move this to be executed after checking for correct card

2019-12-15 12:59 UTC, MateuszKarolChrusciel commented on macao.py
> +
try ctrl+alt+L

2019-12-15 12:59 UTC, MateuszKarolChrusciel commented on macao.py
> +    )
move under classes

2019-12-15 12:59 UTC, MateuszKarolChrusciel commented on macao.py
> +                validation_rule = False
change to "is_compliant_with_rules"

2019-12-15 13:03 UTC, MaciejPoland commented on macao.py
> +                self.table.append(self.deck.pool.pop(random.randint(0, len(self.deck.pool) - 1)))
corrected

2019-12-15 13:03 UTC, MaciejPoland commented on macao.py
> +        while correct_table == False:
corrected

2019-12-15 13:16 UTC, MaciejPoland commented on macao.py
> -        self.table.append(self.deck.pool.pop(random.randint(0, len(self.deck.pool) - 1)))
corrected; later, once is_active will be added to a Class card can be changed to be alligned to class atribute

2019-12-15 13:17 UTC, MaciejPoland commented on macao.py
> +
corrected

2019-12-15 13:18 UTC, MaciejPoland commented on macao.py
> +    )
corrected

2019-12-15 13:19 UTC, MaciejPoland commented on macao.py
> +                validation_rule = False
corrected

2019-12-15 14:33 UTC, MateuszKarolChrusciel approved these changes
IS OK, YAY

2019-12-15 14:33 UTC, MateuszKarolChrusciel commented on macao.py
> +                self.deck.append(card_to_be_drawn)
please change to "self.deck.pool.append(drawn_card)"

or i.e. "card_to_be_laid_out" if u wish

2019-12-16 18:19 UTC, SlawekMaciejewski approved these changes
OK

2019-12-16 18:37 UTC, merged